### ISSUE TITLE
Bug: Permission Denial: reading com.byteowls.capacitor.filesharer.FileSharerProvider uri content://io.ionic.starter.filesharer.fileprovider/capfilesharer/test.pdf from pid=14879, uid=1000 requires the provider be exported, or grantUriPermission()

### ISSUE THREAD

**Issue by Darker1998** [moberwasserlechner/capacitor-filesharer#32]
![image](https://user-images.githubusercontent.com/47914523/132466660-1f83b00e-f9b9-461f-8c58-a1a41672e531.png)

**Comment by moberwasserlechner** [comment]
I released a new version 3.0.0 today

If you can and it is still relevant please test this issue with the new version. (Capacitor 3.0.0 required)

I keep this issue open a few days and close it afterwards if there is no feedback.

BR

**Comment by MrSparklle** [comment]
This issue persists in the last version (3.0.0) downloaded from NPM 2 days ago:

`
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 52005222, pluginId: FileSharer, methodName: share
V/Capacitor: callback: 52005222, pluginId: FileSharer, methodName: share, methodData: {"filename":"Algarve.Fechamento.Sacada.pdf","base64Data":"JVBERi0xLjcKCjQgMCBvYmoKKElkZW50aXR5KQplbmRvYmoKNSAwIG9iagooQWRvYmUpCmVuZG9iago4IDAgb2JqCjw8Ci9GaWx0ZXIgL0ZsYXRlRGVjb2RlCi9MZW5ndGggMTkwODY3Ci9MZW5ndGgxIDU1OTQwNAovVHlwZSAvU3RyZWFtCj4+CnN0cmVhbQp4nOy9B3wcxdUAPrN7vfeq093pdKdy6l2yLJ36qdmWZNmSbdmSLblxtuWGwTZgbDCgAMGAISQkgYRAEhMiyQaLkkDyGQIECEkIJKEEpwABRCAJHUv\/Nzs78skNknz\/\/\/\/7ft+N9Pa9mZ2Z3X1t3szOSggjhGxwkKD++q7mprzX9YNIcd4FCHmONNTWL\/y44q9lCG\/MQkjuaKhtq5Ne8J35CK\/fjRA\/2lTf0HjsyRdeRZJvVyIk+2PTgvldexeOaJDk+z7E\/2RRU1d37bteVTHC2x9HfPaW+V25BV\/\/ackkQvgNuGr\/qg0Dw\/\/IeeduhM77J\/T30qrzt\/nuH\/5tMUK3w3npQ6uH12y4+BW+FKFNzyKkDa8Z2DqMklEArh+D9oY1sQtXK8fe\/hZCd92BUG\/l2qGBwY\/aLxyF\/sn5krVQoP1BErkenEepazdsuyD1ZccnCHFRhNbdfd7Qlo2Xv3\/V2wiXlkHZbbFNqwY+VB\/fDjx5FZov2jBwwXCOOvg3aP84tPdtGNo28NW9t50Pz1MP+cs2DmwY+sYn769AuPy3COVtHd60ddu0G+2H+2sj9Ye3DA2b16Q4Edr9GVz+LYHXsorjz+zb9vIKfeX7yKlAJD341u6nCH6hecf8Tz85sUf5tqIEskrEIZqgnQxNIXxMddunn3xym\/Jtoae45LyblLgz0U3IgCqhHQc4F12BkKlEuC5GvCSMr0NSpJDeIi2ELpMp5p9F+zmkQJxeynGchOckf0Y504+g1F3CHUBq7\/L5UAShTyX0HuTf4EI+hKfJOf6oVEeeFFkkupN3g38B6nQ7yOl\/QOJ\/gO5G\/z8k2Qv\/31wXnq8J\/Q9L\/D9B+\/6ddj9HG85ULhlCt8+qt2d2\/qz9LUC3S\/ai2Gn9XfDF2n9e4l49cz8yGVz3wJnPSb6PVv+71+MnT+HDfNR8xnq9KOnfvsYJ5Ef\/QeJ\/g5b9W+1WoiVnKpdvouUyTLGkCPXPavcp6vsi\/XObUZDRkkMoKPsaCip+c7Ls\/80kqZx9Hdn5KCiZPFkmT0dB\/hgqPq3dKc8qlt2C\/psTfv7MfcoG0S3nup6k7Mwy+yKJe3J2v7wfdZypnvSe2eXcPbP1U\/LaF9dXqRn55a3\/mX6fLfFfRyn\/XX1xd6N6Ac9D9dxfUJSbQE34JyiVuxllcn+d7c\/wchSTLEIx7jUBGmbKP4B8HqrFf6LjMHc58qJESqRESqRE+l+VuFT0IPo\/nPhi9CWUSImUSImUSP9rk+Qn\/\/7aB0vc+6evbXBXo2vPes0NZz7H7UGNKJESKZESKZESKZESKZESKZESKZH+T6czzTE\/L51tnplIiZRIiZRIiZRIiZRIiZRIiZRIiZRIiZRI\/zMSvgUlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIlUiIl0v+INP0ASqRE+r+deBGS6H+SwjLIAcX9HUnQm1CQh3xAkf\/iowUqBVWgGtSI2lEXGkBr0Sa0DZ2PbvNkecp9St8lwac+RZ9yn0qmhf8JdYYWq1AMbTlLCzz9\/vSf+O28Z\/q\/pl+d\/hCp2f+4wS3Tq9664q0rJtOOD\/xhriwsa5A1nfp\/r8SUhEIo68wPig3YhZNxOl6Al+BNeDs+H1+Er8bX4a8iGX5bqPLeab1i4T9okcR9Dh9pS+AkfzP6lxK\/eFZWMkOFZpXXx9HLz94b5mY\/qVgqPq9A02dG+BH0vyPxX7Qi\/iL\/\/+r\/jFZHluy\/fNvWLZuHN23cEDtv\/bq1a1YPDa5csbxv2dIlvT3dC7s6OxbMn9fe1trSHG1qbKivq62JVFfNrZxTUV5WWlKcm5OdlR4KpgZSvA6L0aDXqlVKhVwmlfAcRlkNgcZ+32iof1QSCkSj2SQfGICCgbiC\/lEfFDXOrjPq6xeq+WbXjEDN1afUjNCakZma2OCrRJXZWb6GgG\/06fqAbwIv6egB+pr6QK9vdFKg2wVaEhIyWsj4\/dDC1+BYW+8bxf2+htHG89eONPTXQ39jalVdoG5IlZ2FxlRqINVAjaYHhsdwehUWCC69oWKMQwotuewoH2wYGBxd0NHTUO\/2+3uFMlQn9DUqqxuVC3351pF7Rl\/yjWU9MnL1hAGt7A9rBgODA8t6RvkBaDTCN4yMXDFqDI9mBOpHM3b+2QGPPDSaFahvGA0HoLPWzpkL4FFp0BDwjbyP4OYDk2\/PLhkQS2RBw\/uIkOQRZ9gE5xmN4N7gDuH5\/H5yL1+aiKCVkBnd09FD8z600j2OIrnh3lGun5x5hJ2xdpMze9iZmeb9AT8RVUO\/+Hv+WsfonpW+7CzgvvAbhF847xvlQ\/0rV60leGBoJFBfT\/m2sGc0Ug9EZEB81oaxvFyoP9APD7GOsKGjZzQ3MDxqCdTSClDgIzJY19UjNBGbjVrqRlH\/KrHVaG5DPbkvX8NIfz29QdJXoKPnflQ4\/epYkc99uBAVoV5yH6O2OhBKqGGkZ3D1qLffPQj6udrX4\/aPRnqBfb2BnqFeIqWAYTTjVbicX7ii0Aqe7ZTarDJ5cnlQ4evh3HwvkRYU+BrhEKithBMGEJeQJRKtrfT1YDdi1eAqYg1CzeoHMnywLkpO8aRpXdTt7\/XTdI5bcov3JA2OKuL6MkDBzD3R65z11mhtckMZvoah+rgbnNWpVLxBsbcz3ydHeCFeGFooiDij7BQfBMuFMg66EYqIFB2+UbTA1xMYCvQGQIciC3rIsxFeC\/Jt7Qq0dizpEaQtasnCWTl6vozmRpEfTrMMVwc62Bh2M7EK+SYhP5ONnnK6mZ0OkPsaGRkcQ3yQqLJ7DAuEtO5LvaPzw72B0ZXhgJ\/cZ3bWmAJp\/Av768BWG8HdBRoHAj6Dr3FkYGJ6z8qRsUhkZLihf20F2MVIoHlwJNDVU+kWbr6z5yL3TnJtE2rFrQtroSsO1Y4F8JUdYxF8ZdeSnvthEPNdubBnnMNcXX9t71gqnOu534dQRCjlSCkpJBkfyZCeOiGjEOq7748gtEc4KxEKhPyqCYyEMgUrw2jVBEfLDPRCIeFCEYiMVk1I6JkIqy2BMgUt20Nrp4u1FXDGQM48gDgSZ5KTNI0hwuCIShpRRJQRDaflgKWkaBxKHoC6SowOa7AWu8egz06heALvGVNG3PcLPXWKNfdATVK2Z6YM7pxUi+sIrkcfvPvkE3Qv6TmsQdC\/cIQatSSBFjrWgg7BeNLgGyT6t7t37Uh\/L\/EeyAa6Cr94FAeq0CgXqII7lmlGVYGh2lF1oJaUV5PyalouI+Vy0HxswyBs4nRH+gPgiMFiepAbU1vjSZe+ienphT3+p92TvX6wpWUAS3pGlWEY3KTBFqjXRKAfiptG96waIPeBuntIW3mweVUv2CXrEKo0jyqhB6XYA9RoFNoQe4NGq0DXBgICCcXgOvb0jvaGyUV71vUK9moYRdFAxagsRPuUhsiFcntHTIECwfmArauCVxCkhHtDXT20xA1ZuFgvZZJcA3e+KgCnVvX7qI50gS3TwULlpiVD4PMloSEBVG7xJCKPxQfVWtWoMgc6hF9Cq3OIz5EG5b299OaF3BViBbi2YVQNdxSKY6XYALgDp5rJvcDvFXCrpOpPSDcdE6gzcAG
D/Capacitor: App paused
E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.byteowls.capacitor.filesharer.FileSharerProvider uri content://br.com.residencialalgarve.filesharer.fileprovider/capfilesharer/Algarve.Fechamento.Sacada.pdf from pid=5723, uid=1000 requires the provider be exported, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
`

------------------------------------


```
Ionic:

   Ionic CLI                     : 6.17.1 (/Users/xxx/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.8.1
   @angular-devkit/build-angular : 12.2.7
   @angular-devkit/schematics    : 12.2.7
   @angular/cli                  : 12.2.7
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.3
   @capacitor/android : 3.2.3
   @capacitor/core    : 3.2.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.1

System:

   NodeJS : v14.17.6 (/Users/xxx/.nvm/versions/node/v14.17.6/bin/node)
   npm    : 7.24.0
   OS     : macOS Big Sur
```

**Comment by mishrasatyam** [comment]
I get this error, but I am able to share file successfully.
